### ISSUE TITLE
Riesz s-Energy returns different outputs for same random seed

### ISSUE THREAD

**Issue by LucasAlegre** [anyoptimization/pymoo#638] opened 2024-08-20 09:26 UTC
If you start two different Python processes and run:

`get_reference_directions("energy", 4, 32, seed=42)`

I get different outputs each time. I believe there is something wrong with how the random seed is set.

**Comment by blankjul** [comment] 2024-08-25 21:22
very interesting. I quickly looked into it and yes I can reproduce it that even though the random seed is provided the results don't match.

However, the `np.random.seed(seed)` method seems to be called in all runs.

Need to look a little more into this and will let you know.

**Comment by blankjul** [comment] 2024-08-25 21:30
I think the commit above fixes this now. Can you please check?

**Comment by LucasAlegre** [comment] 2024-08-26 08:20
I cannot install it from source because I'm using python 3.8 and pymoo now requires python>=3.9 :/

**Comment by blankjul** [comment] 2024-11-05 09:03
I will close this issue for now. You can use conda do update your environment if needed. Please reopen the issue if you find the current version does not resolve it.

**Closed by blankjul** 2024-11-05 09:03 UTC

**Comment by LucasAlegre** [comment] 2024-11-05 12:35
Do you have an estimate of when a new release will be on pypi with this fix? Thanks!

**Comment by blankjul** [comment] 2024-11-24 18:40
I usually try to create a release 2-3 times a year. Depending on the number of commits.

Was the fix successful with the current dev version?

**Comment by LucasAlegre** [comment] 2024-11-25 14:14
When following the instructions in the README to install it from source, it installs version 0.6.0.1 and then the fix does not seem to have worked.
