### ISSUE TITLE
Option to validate constrain before compute objetive function

### ISSUE THREAD

**Issue by efirvida** [anyoptimization/pymoo#447] opened 2023-06-20 02:44 UTC
This would be a reasonable feature request, for those cases where the constraint doesn't depend on the objective function in those cases, this would improve the optimization speed. 

First I have to say that I'm new to Pymoo so maybe this is possible now and I don't know how to do it.  For example...I'm using it to optimize a process where the result is obtained by a CFD simulation that takes 2 min for each simulation with my current computational power, I'm testing with a pop size of 5 and max generations 50, I know its no sufficient for any reasonable test, but this low-quality test takes around 12h. In which at least 10-20 generation doesn't match the constraints, so seeing the logs this generation was a total waste of time because the simulations were done which could be skipped by some kind of flag if the constraints were not fulfilled.

here is my simplified sample code:

```python
from pymoo.core.problem import ElementwiseProblem

class MaximizeTorque(ElementwiseProblem):
    def __init__(self, xl, xu ):
        super().__init__(
            n_var=5,
            n_obj=1,
            n_ieq_constr=0,
            n_eq_constr=1,
            xl=xl,
            xu=ux,
            vtype=float,
        )

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = -compute_cfd(x)
        out["H"] = 0 if self.__is_monotonic(x) else 1000

    def  compute_cfd(self, x):
        ...
        return torque

    @staticmethod
    def __is_monotonic(x):
        return np.all(np.diff(x) <= 0)

```

As you can see my constrain are fully independent of the solution the only restriction is that `x1=>x2>=x3...` so there is no new to compute the CFD for those cases where they arent monotonic. Thinking Now I can put a big fixed value to the function like I did in the constrain with 1000, but I don´t know if there is a better way.

**Comment by blankjul** [comment] 2023-06-22 03:50
Yes this is already possible with a simple if statement. Moreover, there is no reason to define a strict equality constraint. It is much better for EAs to define an inequality constraint giving the optimizer a hint of how much the constraint is violated.
Please see the code below (I have kept the equality constraint even though it is not necessary).

```
import numpy as np

from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.core.problem import ElementwiseProblem
from pymoo.optimize import minimize


class MaximizeTorque(ElementwiseProblem):
    def __init__(self, xl, xu):
        super().__init__(
            n_var=5,
            n_obj=1,
            n_ieq_constr=1,
            n_eq_constr=1,
            xl=xl,
            xu=xu,
            vtype=float,
        )

    def _evaluate(self, x, out, *args, **kwargs):
        h = 1 - np.all(np.diff(x) <= 0)
        g = np.maximum(0, np.diff(x)).sum()

        # if feasible
        if g <= 0:
            f = -1 * self.compute_cfd(x)
        else:
            f = np.inf

        out["F"], out["G"], out["H"] = f, g, h

    def compute_cfd(self, _):
        return 1


problem = MaximizeTorque(0, 1)

algorithm = GA(pop_size=100, eliminate_duplicates=True)

res = minimize(problem,
               algorithm,
               seed=1,
               verbose=False)

print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

```

Please let me know if this resolves the issue.

**Comment by efirvida** [comment] 2023-07-03 00:30
@blankjul thanks for your reply, it helps a lot, but I think I need to use another approach to relate my optimization criteria. With your code I can keep the constrains for small number of variables (~7), but I can control that and in some cases I have more than 20, so I think that it's to difficult to the algorithm to consider the constrains for a large number of criteria. So I'm thinking to use some linear or logarithmic functions to relate the variable instead of using condtrains

**Comment by blankjul** [comment] 2023-07-03 03:21
For large scale, LOP is always a good solution. However, 20 variables should be no problem for a GA to handle -- if the problem is defined the right way. 

I am closing this issue. Feel free to add a description later on explaining how you have solved your problem.

**Closed** 2023-07-03 03:22 UTC
Labels: help wanted
