### ISSUE TITLE
Binary compilation with Nuitka

### ISSUE THREAD

**Issue by M4a1x** [anyoptimization/pymoo#417] opened 2023-04-02 15:17 UTC
Hi another issue from me : )

I just noticed that [Nuitka](https://github.com/Nuitka/Nuitka) has issues compiling my programs that have pymoo as a dependency. Looking at the startup errors and glancing at the source I came up with [this pull request](https://github.com/Nuitka/Nuitka/pull/2147), adding `autograd` and `pymoo.cython.*` as implicit dependencies.

I just wanted to let you know so you can have a look if you're interested. I'd be happy to change the PR if you notice something missing or wrong.

Cheers,
Max

**Comment by blankjul** [comment] 2023-04-03 01:39
Hi Max, 
can you elaborate a little bit on what the issue is here? I am not sure if I fully understand yet. Does the compilation of pymoo not work on your system? Or does it only not work in another Nuitka which has pymoo as a dependency?

**Comment by blankjul** [comment] 2023-04-17 03:15
Feel feel to directly do a pull request. I will close this issue for now.

**Closed by blankjul** 2023-04-17 03:15 UTC
Labels: dependencies
