### ISSUE TITLE
Pymoo model error during import

### ISSUE THREAD

**Issue by abubakar0214** [anyoptimization/pymoo#509] opened 2023-11-22 11:08 UTC
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import autograd.numpy as anp
----> 2 from pymoo.model.problem import Problem

ModuleNotFoundError: No module named 'pymoo.model'

And this happen even if you install pymoo

**Comment by blankjul** [comment] 2023-11-23 06:16
I can't reproduce this error.  Can you provide some code for me that I can run to get this error message? 
Can you please check if you are using version 0.6.1?

**Comment by abubakar0214** [comment] 2023-11-24 07:28
Thank you very much sir, i can see that the problem has been solved in the
new version. Please if you have any video tutorial on how í can do multiple
featuré selection on a given dataset pleàse help me sir.

**Comment by abubakar0214** [comment] 2023-11-24 10:09
I am trying to write a feature selection using pymoo here, but i dont know
why i keep having this issue

**Comment by blankjul** [comment] 2023-11-25 22:20
checkout binary optimization for feature selection: https://pymoo.org/customization/binary.html

I will close this issue now.

**Closed by blankjul** 2023-11-25 22:20 UTC
Labels: help wanted
