### ISSUE TITLE
Welded beam test problem Pareto front contains dominated solutions

### ISSUE THREAD

**Issue by The-Alley** [anyoptimization/pymoo#549] opened 2024-01-20 00:26 UTC
Hi,

The default Pareto front of the "Welded beam" test problem contains dominated solutions. This is obviously not the intended behaviour.
```python
from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting
from pymoo.problems import get_problem

problem = get_problem("welded_beam")
Pf = problem.pareto_front()

nds_id = NonDominatedSorting().do(Pf, only_non_dominated_front=True)
Pf_dominated_removed = Pf[nds_id, :]
print("Length of original Pareto front:\t", len(Pf))
print("Length of Pareto front after removing nondominated solution:\t", len(Pf_dominated_removed))
print(Pf[0:10])
```

```
Length of original Pareto front:	 300
Length of Pareto front after removing nondominated solution:	 257
[[2.39   0.0147]
 [2.4    0.0145]
 [2.4    0.0143]
 [2.4    0.0142]
 [2.4    0.0145]
 [2.4    0.0144]
 [2.4    0.0142]
 [2.41   0.0132]
 [2.41   0.0139]
 [2.41   0.0132]] 
```

These are not clearly nondominated solutions. The problem is not about the displaying, these are the exact values you get by calling ```problem.pareto_front()```.

It appears that these values are the rounded version of an actual Pareto front.

Cheers.

**Comment by hudsongeovane** [comment] 2024-01-29 14:08
The problem is already [here](https://raw.githubusercontent.com/anyoptimization/pymoo-data/main/pymoo/pf/welded_beam.pf)

**Comment by blankjul** [comment] 2024-01-30 03:18
I see and agree that truncate this change would make sense.

Can you do me a favor and create a PR for this repo: https://github.com/anyoptimization/pymoo-data
(this is where static data are strored).

I will merge it and then it should directly work after your local cache is refreshed.

**Comment by hudsongeovane** [comment] 2024-01-30 12:43
https://github.com/anyoptimization/pymoo-data/pull/1

**Comment by blankjul** [comment] 2024-02-05 02:20
Thanks I just merged it. I am closing the ticket now. You will have to remove the downloaded file from the cache or reinstall pymoo in a new enviroment. It should then work automatically.

Please reopen the ticket if it does not work.

**Closed by blankjul** 2024-02-05 02:20 UTC
Labels: bug
